# Generated by Django 5.1.5 on 2025-06-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('comType', models.TextField()),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='complaint_image/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('priority', models.TextField()),
            ],
        ),
    ]
