# Generated by Django 5.2.4 on 2025-09-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
