# Generated by Django 5.2.4 on 2025-09-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_complaint_status_workassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
