# Generated by Django 5.2.7 on 2025-10-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_workassignment_is_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='priority',
        ),
    ]
