# Generated by Django 5.1.5 on 2025-06-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.PositiveIntegerField(max_length=10)),
                ('address', models.TextField(default=' ')),
                ('password', models.CharField(default=' ', max_length=8)),
            ],
        ),
    ]
