# Generated by Django 5.1.5 on 2025-06-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_imgs/'),
        ),
    ]
