# Generated by Django 5.1.5 on 2025-06-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registration_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobileno',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
