# Generated by Django 5.1.5 on 2025-06-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_registration_mobileno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_image/'),
        ),
    ]
