# Generated by Django 5.1.5 on 2025-06-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobileno',
            field=models.CharField(max_length=10),
        ),
    ]
