# Generated by Django 5.1.5 on 2025-06-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobileno', models.CharField(max_length=10)),
                ('address', models.TextField(default=' ')),
                ('password', models.CharField(default=' ', max_length=8)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_image/')),
                ('department', models.TextField()),
                ('avaialbility', models.TextField()),
            ],
        ),
    ]
